services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container  # Simplified container name
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Web waits for DB to be healthy before starting
    ports:
      - "3001:3000"  # Map internal port 3000 to host port 3001
    networks:
      - app_network  # Updated network name for consistency

  db:
    image: mysql:latest  # MySQL image with the latest tag
    restart: always
    container_name: db-container  # Simplified container name
    environment:
      MYSQL_DATABASE: app_db  # Changed to generic DB name for tutorial purposes
      MYSQL_ROOT_PASSWORD: password  # Generic password
    volumes:
      - db_data:/var/lib/mysql  # Volume for persistent DB storage
      - ./scripts:/docker-entrypoint-initdb.d  # Scripts to initialize the DB
    networks:
      - app_network  # Updated network name for consistency
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3  # Healthcheck to ensure the DB is ready

volumes:
  db_data:  # Persistent volume for MySQL data

networks:
  app_network:  # Updated network name to make it tutorial-friendly
    driver: bridge